# Generated by Django 6.0.4 on 2026-05-19 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='concern',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='concerns/'),
        ),
    ]
