# Generated by Django 6.0.4 on 2026-05-15 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_concern'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
