# Generated by Django 6.0.4 on 2026-05-19 07:20

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_concern_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concern',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='concerns/'),
        ),
    ]
